version: '3'
services:
  app:
    image: printgoprinterservice
    container_name: printgoprinterservice
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgresql://admin:printgo@postgres:5432/printerservice
    depends_on:
      - postgres

  postgres:
    image: postgres
    container_name: printgoprinterservice
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=printerservice
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=printgo
