version: "3.1"

services:
  printer-api:
    container_name: printer-api
    restart: on-failure
    build: .
    environment:
      DATABASE_URL: ${DATABASE_URL}
      NODE_ENV: development
      PORT: 8001
    volumes:
      - .:/src
    ports:
      - "8001:8001"
    env_file:
      - .env
    networks:
      - printgo_network

volumes:
  printgo_database:

networks:
    printgo_network:
      external: true
